### ISSUE TITLE
stm32f103c8t6编译出错

### ISSUE THREAD

**Issue by feverGeek** [kuresaru/kstm32#1]
> Executing task: sh -c 'export GCC_PATH='/opt/gcc-arm-none-eabi-9-2019-q4-major/bin'; /usr/bin/make' <

/opt/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc -c -mcpu=cortex-m3 -mthumb   -DSTM32F10X_MD -I'/root/Code/STM32F1xx/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/STM32F10x_StdPeriph_Driver/inc' -I'src' -I'src/system' -I'/root/Code/STM32F1xx/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/CoreSupport'  -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/core_cm3.d" -Wa,-a,-ad,-alms=build/core_cm3.lst /root/Code/STM32F1xx/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/CoreSupport/core_cm3.c -o build/core_cm3.o
/tmp/ccbpL884.s: Assembler messages:
/tmp/ccbpL884.s:1008: Error: registers may not be the same -- `strexb r3,r2,[r3]'
/tmp/ccbpL884.s:1068: Error: registers may not be the same -- `strexh r3,r2,[r3]'
make: *** [Makefile:95: build/core_cm3.o] Error 1
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.

**Comment by feverGeek** [comment]
环境应该都配置好了

**Comment by feverGeek** [comment]
是我的gcc版本不对吗

**Comment by kuresaru** [comment]
你没有给cm官方库打补丁...按照readme改一下
